os: linux
sudo: false
dist: trusty

language: java
jdk: oraclejdk8

cache:
    directories:
        - '$HOME/.m2/repository'

install:
    - mvn --batch-mode --show-version --quiet --define skipTests --update-snapshots --file ./releng/org.eclipse.m2m.atl.releng.parent/pom.xml --activate-profiles photon install

script:
    - mvn -B -V -q -f ./releng/org.eclipse.m2m.atl.releng.parent/pom.xml  -P photon package

after_success:
#DEPLOYMENT SCRIPTS